// Steven Jonathan Sihombing
// 24060123120044



import java.util.List;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.swing.DefaultListModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author TUF GAMING
 */
public class Gui4 extends javax.swing.JFrame {
    
    DefaultListModel<String> dlm ;
    List<String> items = new ArrayList<>() ;
    String[] datas = {"buku" , "meja" , "kursi" , "tas" , "pintu"} ;
    Set<String> dataSet = new HashSet<>();
    Map<Integer, String> dataMap = new HashMap<>();
    int mapKeyCounter = 1;




    /**
     * Creates new form Gui2
     */
    public Gui4() {
        initComponents();
        this.dlm = new DefaultListModel<>() ;
        this.ListItem.setModel(dlm) ;

        for (String data : datas){
            dlm.addElement(data);
            updateJumDataTersimpan() ;   
        }
    }
    
    private void addItem(String namaItem){
        dlm.addElement(namaItem) ;
        updateJumDataTersimpan() ;
    }

    private void updateJumDataTersimpan() {
        LabelJumlahData.setText("Jumlah data tersimpan : " + items.size()) ;
        LabelJumlahDataSet.setText("Jumlah data tersimpan : " + dataSet.size());
        LabelDataMap.setText("Jumlah data tersimpan : " + dataMap.size());
    }


    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListItem = new javax.swing.JList<>();
        insertDataButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TextField = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        clearAllButton = new javax.swing.JButton();
        LabelJumlahData = new javax.swing.JLabel();
        saveDataButton = new javax.swing.JButton();
        LabelJumlahDataSet = new javax.swing.JLabel();
        saveSetButton = new javax.swing.JButton();
        insertSet = new javax.swing.JButton();
        saveMapButton = new javax.swing.JButton();
        insertaMapButton = new javax.swing.JButton();
        LabelDataMap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(ListItem);

        insertDataButton.setText("<- insert data list");
        insertDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertDataButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Item name");

        AddButton.setText("add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        updateButton.setText("update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        clearAllButton.setText("clear all");
        clearAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllButtonActionPerformed(evt);
            }
        });

        LabelJumlahData.setText("jLabel2");

        saveDataButton.setText("save to list ->");
        saveDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDataButtonActionPerformed(evt);
            }
        });

        LabelJumlahDataSet.setText("jLabel2");

        saveSetButton.setText("save to set ->");
        saveSetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSetButtonActionPerformed(evt);
            }
        });

        insertSet.setText("<- insert data set");
        insertSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertSetActionPerformed(evt);
            }
        });

        saveMapButton.setText("save to map ->");
        saveMapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMapButtonActionPerformed(evt);
            }
        });

        insertaMapButton.setText("<- insert data map");
        insertaMapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertaMapButtonActionPerformed(evt);
            }
        });

        LabelDataMap.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clearAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(insertDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveSetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(insertSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveMapButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(insertaMapButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelJumlahData, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(LabelJumlahDataSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelDataMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveDataButton)
                            .addComponent(LabelJumlahData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insertDataButton)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelJumlahDataSet)
                            .addComponent(saveSetButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(insertSet)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveMapButton)
                            .addComponent(LabelDataMap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insertaMapButton)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearAllButton)
                    .addComponent(AddButton)
                    .addComponent(updateButton)
                    .addComponent(deleteButton))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertDataButtonActionPerformed
        // TODO add your handling code here:
        dlm.clear() ;
        
        for(String item : items){
            dlm.addElement(item) ;
        }
    }//GEN-LAST:event_insertDataButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        
        addItem(TextField.getText()) ;
        
        TextField.setText("") ;
    }//GEN-LAST:event_AddButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int index = ListItem.getSelectedIndex() ;
        dlm.removeElementAt(index) ;
        
        TextField.setText("") ;
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        int index = ListItem.getSelectedIndex() ;
        String selected = TextField.getText() ;
        dlm.setElementAt(selected, index);
        
        TextField.setText("");
    }//GEN-LAST:event_updateButtonActionPerformed

    private void clearAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllButtonActionPerformed
        // TODO add your handling code here:
        dlm.clear() ;
    }//GEN-LAST:event_clearAllButtonActionPerformed

    private void saveDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDataButtonActionPerformed
        // TODO add your handling code here:
        if(!items.isEmpty()){
            items.clear() ;
        }

        for (int i = 0 ; i < dlm.getSize() ; i++){
            items.add(dlm.getElementAt(i)) ;
        }

        updateJumDataTersimpan();
    }//GEN-LAST:event_saveDataButtonActionPerformed

    private void saveSetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSetButtonActionPerformed
        // TODO add your handling code here:
        dataSet.clear();
        for (int i = 0; i < dlm.size(); i++) {
            dataSet.add(dlm.getElementAt(i));
        }
        updateJumDataTersimpan();

    }//GEN-LAST:event_saveSetButtonActionPerformed

    private void insertSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertSetActionPerformed
        // TODO add your handling code here:
        dlm.clear();
        for (String item : dataSet) {
            dlm.addElement(item);
        }
        updateJumDataTersimpan();
    }//GEN-LAST:event_insertSetActionPerformed

    private void saveMapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMapButtonActionPerformed
        // TODO add your handling code here:
        dataMap.clear();
        mapKeyCounter = 1;
        for (int i = 0; i < dlm.size(); i++) {
            dataMap.put(mapKeyCounter++, dlm.getElementAt(i));
        }
        updateJumDataTersimpan();

    }//GEN-LAST:event_saveMapButtonActionPerformed

    private void insertaMapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertaMapButtonActionPerformed
        // TODO add your handling code here:
        dlm.clear();
        for (String value : dataMap.values()) {
            dlm.addElement(value);
        }
        updateJumDataTersimpan();

    }//GEN-LAST:event_insertaMapButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel LabelDataMap;
    private javax.swing.JLabel LabelJumlahData;
    private javax.swing.JLabel LabelJumlahDataSet;
    private javax.swing.JList<String> ListItem;
    private javax.swing.JTextField TextField;
    private javax.swing.JButton clearAllButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton insertDataButton;
    private javax.swing.JButton insertSet;
    private javax.swing.JButton insertaMapButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveDataButton;
    private javax.swing.JButton saveMapButton;
    private javax.swing.JButton saveSetButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
