/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbc.program;

import jdbc.service.MysqlMahasiswaService ;
import javax.swing.DefaultListModel;
import jdbc.model.Mahasiswa ;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.ListSelectionEvent;


/**
 *
 * @author TUF GAMING
 */
public class JFrameUtama extends javax.swing.JFrame {
    
    static MysqlMahasiswaService service = new MysqlMahasiswaService();
    
    DefaultListModel<String> id ; 
    DefaultListModel<String> nama ; 

    /**
     * Creates new form JFrameUtama
     */
    /*
 * Creates new form JFrameUtama
 */
public JFrameUtama() {
        initComponents();
        this.id = new DefaultListModel<>();
        this.nama = new DefaultListModel<>();

        this.idList.setModel(id);
        this.namaList.setModel(nama);

        // Aktifkan single selection
        idList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        namaList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        // Sinkronkan selection antara idList dan namaList
        idList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    namaList.setSelectedIndex(idList.getSelectedIndex());
                }
            }
        });

        namaList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    idList.setSelectedIndex(namaList.getSelectedIndex());
                }
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        idList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        namaList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        getAllDataButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        textFieldNama = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        idFieldEdit = new javax.swing.JTextField();
        textFieldEdit = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        idFieldDelete = new javax.swing.JTextField();
        textFieldDelete = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        resetIndexButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("Nama");

        jScrollPane1.setViewportView(idList);

        jScrollPane2.setViewportView(namaList);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("KELOLA DATA MAHASISWA");

        getAllDataButton.setText("Ambil Semua Data");
        getAllDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAllDataButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("nama");

        textFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNamaActionPerformed(evt);
            }
        });

        addButton.setText("Tambahkan");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        idFieldEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldEditActionPerformed(evt);
            }
        });

        textFieldEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEditActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        textFieldDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDeleteActionPerformed(evt);
            }
        });

        deleteButton.setText("Hapus");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        resetIndexButton.setText("Reset indeks");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getAllDataButton)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton)
                    .addComponent(textFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(idFieldDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(idFieldEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldEdit)
                            .addComponent(textFieldDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editButton)
                            .addComponent(deleteButton)))
                    .addComponent(resetIndexButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(getAllDataButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idFieldEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idFieldDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButton))
                        .addGap(18, 18, 18)
                        .addComponent(resetIndexButton))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Validasi input tidak kosong
        String nama = textFieldNama.getText();
        Mahasiswa mhs = new Mahasiswa();
        mhs.setNama(nama);

        service.add(mhs);               // simpan ke database
        getAllDataButtonActionPerformed(evt) ;
        textFieldNama.setText("");          // kosongkan field input
        System.out.println("Tambah: " + nama);
    }                                         

    private void idFieldEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldEditActionPerformed

    private void textFieldEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEditActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
    // Pastikan ada item yang dipilih
        if (idList.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan diupdate terlebih dahulu", 
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            // Ambil ID dari list yang dipilih (bukan index list)
            int selectedId = Integer.parseInt(idList.getSelectedValue());
            
            // Ambil data mahasiswa berdasarkan ID
            Mahasiswa dataMahasiswa = service.getById(selectedId);
            if (dataMahasiswa == null) {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan", 
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Update data
            String newNama = textFieldEdit.getText().trim();
            if (newNama.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong", 
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            Mahasiswa updatedMahasiswa = new Mahasiswa(selectedId, newNama);
            service.update(updatedMahasiswa);
            
            // Refresh tampilan
            getAllDataButtonActionPerformed(evt);
            
            // Kosongkan field edit
            textFieldEdit.setText("");
            
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate", 
                "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID tidak valid", 
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }                                           

    private void textFieldDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDeleteActionPerformed

    private void textFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNamaActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // Pastikan ada item yang dipilih
        if (idList.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus terlebih dahulu", 
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            // Ambil ID dari list yang dipilih
            int selectedId = Integer.parseInt(idList.getSelectedValue());
            
            // Konfirmasi sebelum menghapus
            int confirm = JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin menghapus data dengan ID " + selectedId + "?", 
                "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
            
            if (confirm == JOptionPane.YES_OPTION) {
                // Lakukan penghapusan
                service.delete(selectedId);
                
                // Refresh tampilan
                getAllDataButtonActionPerformed(evt);
                
                // Reset index jika tabel kosong
                if (service.isEmpty()) {
                    service.indexReset();
                }
                
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", 
                    "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID tidak valid", 
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }  //GEN-LAST:event_deleteButtonActionPerformed

    private void getAllDataButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Clear existing data in the lists
        id.clear();
        nama.clear();
        
        // Get all Mahasiswa data from service
        List<Mahasiswa> listMahasiswa = service.getAll();
        
        // Populate the lists with data
        for (Mahasiswa mhs : listMahasiswa) {
            id.addElement(String.valueOf(mhs.getId()));
            nama.addElement(mhs.getNama());
        }
    }                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton getAllDataButton;
    private javax.swing.JTextField idFieldDelete;
    private javax.swing.JTextField idFieldEdit;
    private javax.swing.JList<String> idList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> namaList;
    private javax.swing.JButton resetIndexButton;
    private javax.swing.JTextField textFieldDelete;
    private javax.swing.JTextField textFieldEdit;
    private javax.swing.JTextField textFieldNama;
    // End of variables declaration//GEN-END:variables
}
